
BUTTON_刷新_XPATH = '//div/button[@class="ant-btn"]'
BUTTON_筛选_XPATH = '//div[@class="ant-col-12 text-right"]/button[@class="ant-btn ml-10 mb-10"]'
SPAN_>_XPATH = '//div[@class="ant-layout"]/div[@class="bread ant-breadcrumb"]/span/span[@class="ant-breadcrumb-separator"]/span/span[@class="ant-breadcrumb-separator"]/span[@class="ant-breadcrumb-separator"]/span/div[@class="bread ant-breadcrumb"]'
SPAN_>_XPATH = '//div[@class="ant-layout"]/div[@class="bread ant-breadcrumb"]/span/span[@class="ant-breadcrumb-separator"]/span/span[@class="ant-breadcrumb-separator"]/span[@class="ant-breadcrumb-separator"]/span/div[@class="bread ant-breadcrumb"]'
SPAN_>_XPATH = '//div[@class="ant-layout"]/div[@class="bread ant-breadcrumb"]/span/span[@class="ant-breadcrumb-separator"]/span/span[@class="ant-breadcrumb-separator"]/span[@class="ant-breadcrumb-separator"]/span/div[@class="bread ant-breadcrumb"]'
SPAN__XPATH = '//div[@class="ant-spin-nested-loading"]/div/div[@class="ant-spin ant-spin-spinning"]/span[@class="ant-spin-dot"]/div[@class="ant-spin ant-spin-spinning"]/span[@class="ant-spin-dot"]/span[@class="ant-spin-dot"]/div[@class="ant-spin ant-spin-spinning"]/div'
SPAN__XPATH = '//div[@class="ant-tabs-nav-container"]/span[@class="ant-tabs-tab-next ant-tabs-tab-btn-disabled"]'
SPAN__XPATH = '//div[@class="ant-tabs-nav-container"]/span[@class="ant-tabs-tab-prev ant-tabs-tab-btn-disabled"]'
SPAN__XPATH = '//span[@class="ant-tabs-tab-next ant-tabs-tab-btn-disabled"]/span[@class="ant-tabs-tab-next-icon"]'
SPAN__XPATH = '//span[@class="ant-tabs-tab-prev ant-tabs-tab-btn-disabled"]/span[@class="ant-tabs-tab-prev-icon"]'
SPAN_WUMAO_ADMIN_XPATH = '//div[@class="ant-menu-submenu-title"]/span'
SPAN_专票_XPATH = '//div[@class="ant-col-12"]/div[@class="gutter-box"]/div[@class="ant-tag ant-tag-zoom-appear ant-tag-zoom-appear-active"]/span[@class="ant-tag-text"]/div[@class="ant-tag ant-tag-zoom-appear ant-tag-zoom-appear-active"]/span[@class="ant-tag-text"]/span[@class="ant-tag-text"]/div[@class="ant-tag ant-tag-zoom-appear ant-tag-zoom-appear-active"]/div[@class="gutter-box"]'
SPAN_价税合计_XPATH = '//thead[@class="ant-table-thead"]/tr/th[@class="text-left"]/span/th[@class="text-left"]/span/span/th[@class="text-left"]/tr'
SPAN_全部_XPATH = '//div[@class="ant-col-12"]/div[@class="gutter-box"]/div[@class="ant-tag ant-tag-zoom-appear ant-tag-zoom-appear-active"]/span[@class="ant-tag-text"]/div[@class="ant-tag ant-tag-zoom-appear ant-tag-zoom-appear-active"]/span[@class="ant-tag-text"]/span[@class="ant-tag-text"]/div[@class="ant-tag ant-tag-zoom-appear ant-tag-zoom-appear-active"]/div[@class="gutter-box"]'
SPAN_刷新_XPATH = '//button[@class="ant-btn"]/span'
SPAN_发票信息_XPATH = '//span/span[@style="margin-left: 51px;"]'
SPAN_发票信息_XPATH = '//thead[@class="ant-table-thead"]/tr/th[@class="text-left"]/span/th[@class="text-left"]/span/span/th[@class="text-left"]/tr'
SPAN_发票管理>_XPATH = '//div[@class="bill-panel"]/div[@class="ant-layout"]/div[@class="bread ant-breadcrumb"]/span/div[@class="bread ant-breadcrumb"]/span/span/div[@class="bread ant-breadcrumb"]/div[@class="ant-layout"]'
SPAN_发票管理_XPATH = '//div[@class="ant-layout"]/div[@class="bread ant-breadcrumb"]/span/span[@class="ant-breadcrumb-link"]/span/span[@class="ant-breadcrumb-link"]/span[@class="ant-breadcrumb-link"]/span/div[@class="bread ant-breadcrumb"]'
SPAN_操作_XPATH = '//th[@class="text-right"]/span'
SPAN_普票_XPATH = '//div[@class="ant-col-12"]/div[@class="gutter-box"]/div[@class="ant-tag ant-tag-zoom-appear ant-tag-zoom-appear-active"]/span[@class="ant-tag-text"]/div[@class="ant-tag ant-tag-zoom-appear ant-tag-zoom-appear-active"]/span[@class="ant-tag-text"]/span[@class="ant-tag-text"]/div[@class="ant-tag ant-tag-zoom-appear ant-tag-zoom-appear-active"]/div[@class="gutter-box"]'
SPAN_状态_XPATH = '//thead[@class="ant-table-thead"]/tr/th[@class="text-left"]/span/th[@class="text-left"]/span/span/th[@class="text-left"]/tr'
SPAN_筛选_XPATH = '//button[@class="ant-btn ml-10 mb-10"]/span'
SPAN_进项发票管理>_XPATH = '//div[@class="bill-panel"]/div[@class="ant-layout"]/div[@class="bread ant-breadcrumb"]/span/div[@class="bread ant-breadcrumb"]/span/span/div[@class="bread ant-breadcrumb"]/div[@class="ant-layout"]'
SPAN_进项发票管理_XPATH = '//div[@class="ant-layout"]/div[@class="bread ant-breadcrumb"]/span/span[@class="ant-breadcrumb-link"]/span/span[@class="ant-breadcrumb-link"]/span[@class="ant-breadcrumb-link"]/span/div[@class="bread ant-breadcrumb"]'
SPAN_进项发票管理_XPATH = '//span[@class="ant-breadcrumb-link"]/span[@class="text_active"]'
SPAN_首页>_XPATH = '//div[@class="bill-panel"]/div[@class="ant-layout"]/div[@class="bread ant-breadcrumb"]/span/div[@class="bread ant-breadcrumb"]/span/span/div[@class="bread ant-breadcrumb"]/div[@class="ant-layout"]'
SPAN_首页_XPATH = '//div[@class="ant-layout"]/div[@class="bread ant-breadcrumb"]/span/span[@class="ant-breadcrumb-link"]/span/span[@class="ant-breadcrumb-link"]/span[@class="ant-breadcrumb-link"]/span/div[@class="bread ant-breadcrumb"]'
SPAN_首页_XPATH = '//ul[@class="ant-menu ant-menu-light ant-menu-root ant-menu-inline"]/li[@class="ant-menu-item"]/div/span/div/span/span/div/li[@class="ant-menu-item"]'
